name: Python Game CI

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run game check
        run: |
          python main.py

      - name : Run tests
        run : |
          python test.py

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  handle-failure:
    needs: build
    if: failure() && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get current commit SHA
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Create failure branch and push
        run: |
          git checkout -b failure-${{ steps.commit.outputs.sha }}
          git push origin failure-${{ steps.commit.outputs.sha }}

      - name: Revert last commit on develop
        run: |
          git checkout develop
          git revert --no-edit ${{ steps.commit.outputs.sha }}
          git push origin develop
